name: mlproject
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - scikit-learn
  - jupyter
  - ipykernel
  - pip
  - pip:
    - -e .